<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Payment.Domain\ECommerce.Payment.Domain.csproj" />
    <ProjectReference Include="..\ECommerce.Payment.Application\ECommerce.Payment.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ECommerce.BuildingBlocks.Contracts\ECommerce.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ECommerce.BuildingBlocks.Persistence\ECommerce.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\ECommerce.BuildingBlocks.EventBus\ECommerce.BuildingBlocks.EventBus.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
