<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\ECommerce.BuildingBlocks.Contracts\ECommerce.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ECommerce.BuildingBlocks.Localization\ECommerce.BuildingBlocks.Localization.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ECommerce.BuildingBlocks.Observability\ECommerce.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\ECommerce.BuildingBlocks.Security\ECommerce.BuildingBlocks.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ocelot" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="ocelot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="ocelot.Docker.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
