@ECommerce.ApiGateway_HostAddress = http://localhost:5080

GET {{ECommerce.ApiGateway_HostAddress}}/health/live
Accept: application/json

###

GET {{ECommerce.ApiGateway_HostAddress}}/gateway/catalog/products
Accept: application/json
