@ECommerce.Catalog.Api_HostAddress = http://localhost:5283

GET {{ECommerce.Catalog.Api_HostAddress}}/api/v1/products
Accept: application/json
Accept-Language: en

###

GET {{ECommerce.Catalog.Api_HostAddress}}/api/v1/products/00000000-0000-0000-0000-000000000000
Accept: application/json
Accept-Language: tr

###
