<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\ECommerce.BuildingBlocks.Contracts\ECommerce.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ECommerce.BuildingBlocks.EventBus\ECommerce.BuildingBlocks.EventBus.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ECommerce.BuildingBlocks.Observability\ECommerce.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\ECommerce.BuildingBlocks.Security\ECommerce.BuildingBlocks.Security.csproj" />
    <ProjectReference Include="..\..\tools\ECommerce.RuntimeChecks\ECommerce.RuntimeChecks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
