<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.BuildingBlocks.Contracts\ECommerce.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\ECommerce.BuildingBlocks.Localization\ECommerce.BuildingBlocks.Localization.csproj" />
  </ItemGroup>

</Project>
